// Export all content for easy imports
export { heroContent } from './hero-content'
export { headerContent } from './header-content'
export { featuresContent } from './features-content'
export { problemContent } from './problem-content'
export { solutionContent } from './solution-content'
export { howItWorksContent } from './how-it-works-content'
export { socialProofContent } from './social-proof-content'
export { contactContent } from './contact-content'
export { chatWidgetContent } from './chat-widget-content'
export { industryShowcaseContent } from './industry-showcase-content'
export { implementationTimelineContent } from './implementation-timeline-content'
export { enhancedGuaranteeContent } from './enhanced-guarantee-content'
