version: '3.8'
services:
  # Private Docker Registry
  registry:
    image: registry:2
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - '0.0.0.0:5000:5000'
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    volumes:
      - registry_data:/var/lib/registry
      - registry_auth:/auth
    networks:
      - registry_network

  teamhub:
    image: localhost:5000/teamhub:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PG_PASSWORD=${PG_PASSWORD}
      # Add other env vars here, or use secrets/configs
    networks:
      - registry_network
    depends_on:
      - registry

volumes:
  registry_data:
  registry_auth:

networks:
  registry_network:
    driver: overlay
