version: '3.8'
services:
  # Add nginx reverse proxy service
  nginx:
    image: nginx:alpine
    deploy:
      replicas: 1
    ports:
      - '80:80'
      - '443:443'
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    networks:
      - registry_network
    depends_on:
      - teamhub
      - registry

  # Private Docker Registry
  registry:
    image: registry:2
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    # Remove external port exposure - only internal access
    expose:
      - '5000'
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    volumes:
      - registry_data:/var/lib/registry
      - registry_auth:/auth
    networks:
      - registry_network

  teamhub:
    image: localhost:5000/teamhub:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
    # Remove external port exposure - only internal access
    expose:
      - '3000'
    environment:
      - NODE_ENV=production
      - PG_PASSWORD=${PG_PASSWORD}
      # Add other env vars here, or use secrets/configs
    networks:
      - registry_network
    depends_on:
      - registry

configs:
  nginx_config:
    external: true
    name: teamhub_nginx_config_v4

volumes:
  registry_data:
  registry_auth:

networks:
  registry_network:
    driver: overlay
