version: 0.1
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
  http2:
    disabled: true
  # Optimize for tunnel connections
  net: tcp
  # Increase timeouts for tunnel connections
  timeout:
    read: 300s
    write: 300s
    idle: 300s
  # Reduce request size for tunnel compatibility
  maxrequestsize: 10485760 # 10MB chunks
  # Add host configuration for external access
  host: https://r1.teamxagents.com
auth:
  htpasswd:
    realm: Registry Realm
    path: /auth/htpasswd
# Health check endpoint
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
