import { Feature, ModelInfo } from '../modelRegistry'

export const falModels: ModelInfo[] = [
  {
    id: 'fal:flux-pro-kontext-max-text-to-image',
    features: [Feature.TextToImage],
    displayName: 'FLUX.1 Kontext Max',
    provider: 'fal',
    model: 'flux-pro-kontext-max-text-to-image',
  },
  {
    id: 'fal:flux-pro-kontext-text-to-image',
    features: [Feature.TextToImage],
    displayName: 'FLUX.1 Kontext',
    provider: 'fal',
    model: 'flux-pro-kontext-text-to-image',
  },
  {
    id: 'fal:imagen4-preview',
    features: [Feature.TextToImage],
    displayName: 'Imagen 4 Preview',
    provider: 'fal',
    model: 'imagen4-preview',
  },
  {
    id: 'fal:hidream-i1-full',
    features: [Feature.TextToImage],
    displayName: 'HiDream-I1 Full',
    provider: 'fal',
    model: 'hidream-i1-full',
  },
  {
    id: 'fal:hidream-i1-dev',
    features: [Feature.TextToImage],
    displayName: 'HiDream-I1 Dev',
    provider: 'fal',
    model: 'hidream-i1-dev',
  },
  {
    id: 'fal:hidream-i1-fast',
    features: [Feature.TextToImage],
    displayName: 'HiDream-I1 Fast',
    provider: 'fal',
    model: 'hidream-i1-fast',
  },
  {
    id: 'fal:imagen3',
    features: [Feature.TextToImage],
    displayName: 'Imagen 3',
    provider: 'fal',
    model: 'imagen3',
  },
  {
    id: 'fal:imagen3-fast',
    features: [Feature.TextToImage],
    displayName: 'Imagen 3 Fast',
    provider: 'fal',
    model: 'imagen3-fast',
  },
  {
    id: 'fal:bria-text-to-image-hd',
    features: [Feature.TextToImage],
    displayName: 'Bria Text-to-Image HD',
    provider: 'fal',
    model: 'bria-text-to-image-hd',
  },
  {
    id: 'fal:bria-text-to-image-base',
    features: [Feature.TextToImage],
    displayName: 'Bria Text-to-Image Base',
    provider: 'fal',
    model: 'bria-text-to-image-base',
  },
  {
    id: 'fal:dia-tts',
    features: [Feature.TextToSpeech],
    displayName: 'Dia Text to Speech',
    provider: 'fal',
    model: 'dia-tts',
  },
  {
    id: 'fal:veo3-text-to-video',
    features: [Feature.VideoGeneration],
    displayName: 'Veo 3',
    provider: 'fal',
    model: 'veo3-text-to-video',
  },
  {
    id: 'fal:kling-video-v2.1-master-image-to-video',
    features: [Feature.VideoGeneration],
    displayName: 'Kling 2.1 Master',
    provider: 'fal',
    model: 'kling-video-v2.1-master-image-to-video',
  },
  {
    id: 'fal:wan-pro-image-to-video',
    features: [Feature.VideoGeneration],
    displayName: 'Wan-2.1 Pro',
    provider: 'fal',
    model: 'wan-pro-image-to-video',
  },
  {
    id: 'fal:wan-i2v-image-to-video',
    features: [Feature.VideoGeneration],
    displayName: 'Wan-2.1',
    provider: 'fal',
    model: 'wan-i2v-image-to-video',
  },
  {
    id: 'fal:pixverse-v4.5-image-to-video',
    features: [Feature.VideoGeneration],
    displayName: 'PixVerse v4.5',
    provider: 'fal',
    model: 'pixverse-v4.5-image-to-video',
  },
]
