import { Feature, ModelInfo } from '../modelRegistry'

export const openaiModels: ModelInfo[] = [
  {
    id: 'openai:gpt-4o',
    features: [Feature.ChatAPI],
    displayName: 'GPT-4o',
    provider: 'openai',
    model: 'gpt-4o',
  },
  {
    id: 'openai:gpt-4.1',
    features: [Feature.ChatAPI],
    displayName: 'GPT-4.1',
    provider: 'openai',
    model: 'gpt-4.1',
  },
  {
    id: 'openai:gpt-4.1-mini',
    features: [Feature.ChatAPI],
    displayName: 'GPT-4.1 Mini',
    provider: 'openai',
    model: 'gpt-4.1-mini',
  },
  {
    id: 'openai:gpt-4.1-nano',
    features: [Feature.ChatAPI],
    displayName: 'GPT-4.1 Nano',
    provider: 'openai',
    model: 'gpt-4.1-nano',
  },
  {
    id: 'openai:o3',
    features: [Feature.ChatAPI],
    displayName: 'o3',
    provider: 'openai',
    model: 'o3',
  },
  {
    id: 'openai:o3-pro',
    features: [Feature.ChatAPI],
    displayName: 'o3 Pro',
    provider: 'openai',
    model: 'o3-pro',
  },
  {
    id: 'openai:o4-mini',
    features: [Feature.ChatAPI],
    displayName: 'o4 Mini',
    provider: 'openai',
    model: 'o4-mini',
  },
  {
    id: 'openai:gpt-3.5-turbo',
    features: [Feature.ChatAPI],
    displayName: 'GPT-3.5 Turbo',
    provider: 'openai',
    model: 'gpt-3.5-turbo',
  },
  {
    id: 'openai:gpt-3.5-turbo-16k',
    features: [Feature.ChatAPI],
    displayName: 'GPT-3.5 Turbo 16k',
    provider: 'openai',
    model: 'gpt-3.5-turbo-16k',
  },
  {
    id: 'openai:text-embedding-ada-002',
    features: [Feature.Embeddings],
    displayName: 'Ada Embedding',
    provider: 'openai',
    model: 'text-embedding-ada-002',
  },
  {
    id: 'openai:text-embedding-3-large',
    features: [Feature.Embeddings],
    displayName: 'Embedding 3 Large',
    provider: 'openai',
    model: 'text-embedding-3-large',
  },
  {
    id: 'openai:text-embedding-3-small',
    features: [Feature.Embeddings],
    displayName: 'Embedding 3 Small',
    provider: 'openai',
    model: 'text-embedding-3-small',
  },
  {
    id: 'openai:gpt-image-1',
    features: [Feature.TextToImage],
    displayName: 'GPT Image 1',
    provider: 'openai',
    model: 'gpt-image-1',
  },
  {
    id: 'openai:dall-e-3',
    features: [Feature.TextToImage],
    displayName: 'DALL·E 3',
    provider: 'openai',
    model: 'dall-e-3',
  },
  {
    id: 'openai:whisper-1',
    features: [Feature.SpeechToText],
    displayName: 'Whisper',
    provider: 'openai',
    model: 'whisper-1',
  },
  {
    id: 'openai:tts-1',
    features: [Feature.TextToSpeech],
    displayName: 'TTS-1',
    provider: 'openai',
    model: 'tts-1',
  },
  {
    id: 'openai:tts-1-hd',
    features: [Feature.TextToSpeech],
    displayName: 'TTS-1 HD',
    provider: 'openai',
    model: 'tts-1-hd',
  },
]
